language: python
sudo: false
dist: xenial

install:
    - pip install pytest
    - pip install numpy
    - pip install codecov
    - pip install pytest-cov
script:
    - pytest -v -s --cov=./
after_success:
    - codecov
